
CREATE DATABASE musicplanet;


CREATE TABLE Songs (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL,
artist VARCHAR(30) NOT NULL,
year VARCHAR(30) NOT NULL,
album VARCHAR(30) NOT NULL
);
